### PR TITLE
Add reveal-md to slide resources

### PR DESCRIPTION
**Pull request by Lionex**
Mostly a time saver for the time-strapped like myself, reveal-md allows for the writing of reveal.js presentations as a single markdown file, while still retaining the ability to do some more complicated stuff with markdown's html fallback capabilities.

### CODE REVIEW

**Comment by PandelisZ** [comment]
Wicked! I didnt know this existed. I always end up jerry rigging a static site generator with reveal js this looks like a vast improvement to my methods :P

**Comment by BlueHatbRit** [comment]
I think we've already got FSReveal on there as well which uses Markdown and F# (don't knock it). This looks much simpler, maybe we should remove FSReveal and just have Reveal-MD?

**Comment by Lionex** [comment]
@BlueHatbRit I'm sure not everyone wants to use `Node.js`

**Comment by BlueHatbRit** [comment]
> I'm sure not everyone wants to use `Node.js`

@Lionex fair point! We'll leave the option there then 👍

**Pull request merged**
