### PR TITLE
Add mocha test to check validity of all external links

### PR DESCRIPTION
**Pull request by BlueHatbRit**
I've created a package.json with some relevant information to enable us to run it as a normal node project on travis later on. I've added a couple libraries including mocha and should, and I've created a test for all external links. The original proposed library had to be ditched as it would try to check relative and anchor links which isn't so helpful right now.

I've also just added a `.travis.yml` file, if we enable builds on "Branch Updates" and "Pull Requests" then it'll build all PR pushes once plus merges into master as we want.

The tests are quite quick right now so I suggest we include them in the PR process for now.

## Notes:

* In the package.json I listed the project as "UNLICENSED" as we don't have a license right now. Do we want to consider adding one now or in the future?
* I've set the author as "GitHub Campus Experts" with no email address for now rather than forcing responsibility onto someone.

This implements #12, cc @PandelisZ & @joenash

### CODE REVIEW

**Comment by PandelisZ** [comment]
Darn, i was just about to review this today

**Comment by BlueHatbRit** [comment]
I was wondering who'd show up first, you or Joe 😂 cleaning out old PR's from my list!

**Comment by PandelisZ** [comment]
Sorry had allot of my plate for 4 years, lots of PRs to review.

**Comment by BlueHatbRit** [comment]
I see how it is, new priorities and all that :(

**Comment by BlueHatbRit** [comment]
2017, when I still had had hope that one of you would review and merge this PR

image

**Pull request closed without merging**
